
name: CI-format-check

on:
  push:
    paths:
      - '**.h'
      - '**.c'
      - '.github/workflows/check-format.yml'
      - '.clang-format'
  pull_request:
    paths:
      - '**.h'
      - '**.c'
      - '.github/workflows/check-format.yml'
      - '.clang-format'

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: DoozyX/clang-format-lint-action@master
      with:
        source: '.'
        extensions: 'h,c'
        clangFormatVersion: 15
        inplace: False
