name: CI-format-check

on:
  push:
  pull_request:

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get install git make clang-format

    - uses: actions/checkout@v2

    - name: Check format -> make format-check
      run: make format-check
