name: CI-compile

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip gawk

    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Get version
      id: version
      run: echo "::set-output name=version::$(make oplversion)"

    - name: Compile -> make clean release
      run: |
        make clean release
 
    - name: Upload release artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: OPNPS2LD
        path: OPNPS2LD-*.ZIP

    - name: Create detailed changelog
      run: sh ./make_changelog.sh

    - name: Upload variants artifact changelog
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: OPNPS2LD-VARIANTS
        path: |
          DETAILED_CHANGELOG
          CREDITS
          LICENSE
          README.md

  build-variants:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    strategy:
      matrix:
        t10k: [0, 1]
        igs: [0, 1]
        pademu: [0, 1]
        rtl: [0, 1]
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git gawk

    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Get version
      id: version
      run: echo "::set-output name=version::$(make oplversion)"

    - name: Compile -> make RTL=${{ matrix.rtl }} IGS=${{ matrix.igs }} PADEMU=${{ matrix.pademu }} DTL_T10000=${{ matrix.t10k }}
      run: |
        make V=1 --trace SHELL='sh -x' RTL=${{ matrix.rtl }} IGS=${{ matrix.igs }} PADEMU=${{ matrix.pademu }} DTL_T10000=${{ matrix.t10k }} NOT_PACKED=1
        mv opl.elf OPNPS2LD-RTL=${{ matrix.rtl }}-IGS=${{ matrix.igs }}-PADEMU=${{ matrix.pademu }}-DTL_T10000=${{ matrix.t10k }}-${{ steps.version.outputs.version }}.ELF

    - name: Upload variants artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: OPNPS2LD-VARIANTS
        path: |
          OPNPS2LD-RTL*.ELF

  create-release:
    needs: [build, build-variants]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Download release artifact
      uses: actions/download-artifact@v1
      with:
        name: OPNPS2LD

    - name: Download variants artifact
      uses: actions/download-artifact@v1
      with:
        name: OPNPS2LD-VARIANTS

    - name: Create release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest development builds"
        files: |
          OPNPS2LD/OPNPS2LD-LATEST.ZIP
          OPNPS2LD-VARIANTS/OPNPS2LD-VARIANTS-LATEST.ZIP
