name: CI-OPLTestISO

on:
  push:
    paths:
      - '.github/workflows/OPLTestISO.yml'
      - 'labs/opltestiso/**'
  workflow_dispatch:

jobs:
  build-opltestiso:
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew:main
    steps:
    - name: Install dependencies
      run:  apk add cdrkit

    - name: git checkout
      uses: actions/checkout@v4

    - run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow

    - name: make ISO
      run: |
          cd labs/opltestiso_ar/
          make iso

    - name: Upload release artifact ISO
      uses: actions/upload-artifact@v4
      with:
        name: OPLTESTISO_AR
        path: |
           labs/opltestiso_ar/*.iso
